FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libgl1 \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PIP_NO_CACHE_DIR=1 \
    PYTHONUNBUFFERED=1

RUN pip install --upgrade pip && \
    pip install torch --index-url https://download.pytorch.org/whl/cpu

RUN pip install \
    marker-pdf==1.8.2 \
    fastapi \
    uvicorn[standard] \
    python-multipart

COPY main.py .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--log-level", "info"]

# docker build -t marker-api-cpu -f Dockerfile.cpu .
# docker run -p 8080:8080 marker-api-cpu
